services:
    enqueue.consumption.doctrine_clear_identity_map_extension:
        class: 'Enqueue\Bundle\Consumption\Extension\DoctrineClearIdentityMapExtension'
        public: false
        arguments:
            - '@doctrine'
        tags:
            - { name: 'enqueue.consumption.extension' }
