services:
    enqueue.consumption.signal_extension:
        class: 'Enqueue\Consumption\Extension\SignalExtension'
        public: false
        tags:
            - { name: 'enqueue.consumption.extension' }